
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: diego
  password: 12345
  host: localhost
  port: 5432
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: AppMedicamento

  
test:
  <<: *default
  database: App-Medicamentos_test


production:
  <<: *default
  database: App-Medicamentos_production
  username: App-Medicamentos
  password: <%= ENV['APP-MEDICAMENTOS_DATABASE_PASSWORD'] %>
